source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'AutoCompleteTextField_Example', :exclusive => true do
  pod 'AutoCompleteTextField', :path => '../'
end

target 'AutoCompleteTextField_Tests', :exclusive => true do
  pod 'AutoCompleteTextField', :path => '../'

  
end
